### ISSUE TITLE
Relaunched ABI tracker for ADG

### ISSUE THREAD

**Issue by lvc** [ntd/adg#2]
Hello Nicola,

The ABI tracker for ADG has been relaunched here: https://abi-laboratory.pro/tracker/timeline/adg/

Instead of an old one: http://upstream.rosalinux.ru/versions/adg.html

![adg-1](https://cloud.githubusercontent.com/assets/1517837/25325967/1478b1bc-28df-11e7-8acf-45c3b83a4edb.png)
![adg-2](https://cloud.githubusercontent.com/assets/1517837/25325970/183d0db6-28df-11e7-8d12-d7b416f4510b.png)

## Environment
* Linux x86_64
* GCC 4.9
* ADG 0.6.6 and higher

**Comment by ntd** [comment]
Many thanks: I will add a backlink from the project page.

I must admit that your project significantly improved the quality of the ADG interface.

**Comment by ntd** [comment]
> ... I will add a backlink from the project page.

Added a dedicated section to the [download page](http://adg.entidi.com/home/download#TOC-2).
