### ISSUE TITLE
Integrating into SolveSpace

### ISSUE THREAD

**Issue by ghost** [ntd/adg#3]
Could it be useful to integrate *ADG* into *SolveSpace* CAD?

- https://github.com/solvespace/solvespace

**Comment by ntd** [comment]
I don't know... I'd say yes. But I also think this question could be better answered by the solvespace folks.

**Comment by ghost** [comment]
I just asked because actual SolveSpace implementation for render/export 2D view to PDF/SVG/PNG is little limited and has issues.

ADG could export vector to PDF?

**Comment by ntd** [comment]
> ADG could export vector to PDF?

Yes, of course: any valid [cairo backend](https://www.cairographics.org/backends/) is a valid ADG export and the primitives are rasterized only when strictly needed. The big missing one is DXF because cairo does not have that backend.
